CREATE DATABASE dbEmployee 
ON PRIMARY 
( 
NAME=dbEmployee_DAT, 
FILENAME= 
'C:\DB_B6638146\dbEmployee.mdf', 
SIZE=5, 
MAXSIZE=20, 
FILEGROWTH=1 
) 
LOG ON
(
NAME= dbEmployee_LOG,
FILENAME= 'C:\DB_B6638146\dbEmployee.ldf',
SIZE=5,
MAXSIZE=5,
FILEGROWTH=1
)